### ISSUE TITLE
Anki 2.1.30

### ISSUE THREAD

**Issue by orginux** [vi3itor/lingualeoanki#17]
`Import from Lingualeo` > `Import all words`

```
Error:
Anki 2.1.30 (06a69c25) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-13 11:08:17
Причиной могли послужить: ⁨Import Words from LinguaLeo to Anki 2⁩

Caught exception:
Traceback (most recent call last):
  File "/home/orginux/.local/share/Anki2/addons21/1411073333/gui.py", line 347, in download_words
    self.start_downloading_media(filtered)
  File "/home/orginux/.local/share/Anki2/addons21/1411073333/gui.py", line 375, in start_downloading_media
    self.model = utils.prepare_model(mw.col, utils.fields, styles.model_css)
  File "/home/orginux/.local/share/Anki2/addons21/1411073333/utils.py", line 75, in prepare_model
    model = create_new_model(collection, fields, model_css)
  File "/home/orginux/.local/share/Anki2/addons21/1411073333/utils.py", line 45, in create_new_model
    model['tags'].append("LinguaLeo")
KeyError: 'tags'
```
![image](https://user-images.githubusercontent.com/24264965/90187797-117d3180-ddc3-11ea-9b2b-6d1557fa6ac5.png)

```
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Button Colours Good Again ['2494384865', 2020-02-09T15:18, 'None', '']
    Import Words from LinguaLeo to Anki 2 ['1411073333', 2020-07-11T08:49, 'None', mod]
    Replay buttons on card ['498789867', 2019-03-16T16:23, 'None', '']
    True Retention ['613684242', 2019-03-16T16:24, 'None', '']
```

**Comment by vi3itor** [comment]
Hi! Thanks for the heads up. I'll look into it in the upcoming days.

**Comment by vi3itor** [comment]
Fixed, please update.
