### ISSUE TITLE
Anki 2.1.30

### ISSUE THREAD

**Issue by dashcats** [vi3itor/lingualeoanki#18]
Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-16 16:14:50

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 347, in download_words
    self.start_downloading_media(filtered)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 375, in start_downloading_media
    self.model = utils.prepare_model(mw.col, utils.fields, styles.model_css)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 75, in prepare_model
    model = create_new_model(collection, fields, model_css)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 45, in create_new_model
    model['tags'].append("LinguaLeo")
KeyError: 'tags'

**Comment by vi3itor** [comment]
Fixed, please try now.
