### ISSUE TITLE
Error in the downloading process on Linux

### ISSUE THREAD

**Issue by kpspu** [vi3itor/lingualeoanki#21]
### Actions

1. Download words from specific dictionary on Lingualeo
2. Wait till it checks repeats
3. Encounter this error
4. Everything is downloaded if I am not wrong

### Error message

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-01 19:32:41
Add-ons possibly involved: ⁨Import Words from LinguaLeo to Anki 2⁩

Caught exception:
Traceback (most recent call last):
  File "/home/mrsir/.local/share/Anki2/addons21/1411073333/gui.py", line 408, in add_word
    utils.add_word(word, self.model)
  File "/home/mrsir/.local/share/Anki2/addons21/1411073333/utils.py", line 191, in add_word
    collection.addNote(note)
  File "anki/collection.py", line 382, in addNote
  File "anki/collection.py", line 362, in add_note
  File "anki/notes.py", line 58, in to_backend_note
TypeError: None has type NoneType, but expected one of: bytes, unicode

**Comment by vi3itor** [comment]
The issue should be fixed now. Please check the new version.
